In [2]:
import numpy as np
import pandas as pd

import matplotlib as mpl
import matplotlib.pyplot as plt

%matplotlib inline

ruta_ratings = './ratings.dat'     # AQU√ç PONER LA RUTA DEL FICHERO
ruta_users = './users.dat'
ruta_movies= './movies.dat'
## fuente: http://www.michaeltsmith.org.uk/ipython/Lesson%201,%20%28detour%29%20Python,%20pandas%20and%20Movie%20Ratings%20%28MovieLens%29.html

In [68]:
from datetime import datetime
dateparse = lambda x: datetime.fromtimestamp(float(x))

valoraciones = pd.read_csv(ruta_ratings, sep = '::', header = None,
                         names = ['user','movie','rating','time'],
                         engine ='python',
                         parse_dates=[3], date_parser=dateparse)

In [69]:

usuarios = pd.read_csv(ruta_users, sep = '::', header = None,
                         names = ['user','gender','age','occupation','zip'],
                         engine ='python')

In [72]:
##http://www.michaeltsmith.org.uk/ipython/Lesson%201,%20%28detour%29%20Python,%20pandas%20and%20Movie%20Ratings%20%28MovieLens%29.html
peliculas = pd.read_csv(ruta_movies, sep = '::', header = None,
                         names = ['movie','title','genre'],
                         engine ='python')
movielens = pd.merge(pd.merge(valoraciones,usuarios),peliculas)
movielens

,user,movie,rating,time,gender,age,occupation,zip,title,genre
0,1,1193,5,2000-12-31 23:12:40,F,1,10,48067,One Flew Over the Cuckoo's Nest (1975),Drama
1,2,1193,5,2000-12-31 22:33:33,M,56,16,70072,One Flew Over the Cuckoo's Nest (1975),Drama
2,12,1193,4,2000-12-31 00:49:39,M,25,12,32793,One Flew Over the Cuckoo's Nest (1975),Drama
3,15,1193,4,2000-12-30 19:01:19,M,25,7,22903,One Flew Over the Cuckoo's Nest (1975),Drama
4,17,1193,5,2000-12-30 07:41:11,M,50,1,95350,One Flew Over the Cuckoo's Nest (1975),Drama
5,18,1193,4,2000-12-30 07:02:48,F,18,3,95825,One Flew Over the Cuckoo's Nest (1975),Drama
6,19,1193,5,2001-02-21 05:48:56,M,1,10,48073,One Flew Over the Cuckoo's Nest (1975),Drama
7,24,1193,5,2000-12-30 01:38:29,F,25,7,10023,One Flew Over the Cuckoo's Nest (1975),Drama
8,28,1193,3,2000-12-29 22:26:34,F,25,1,14607,One Flew Over the Cuckoo's Nest (1975),Drama
9,33,1193,5,2001-01-03 22:36:05,M,45,3,55421,One Flew Over the Cuckoo's Nest (1975),Drama
10,39,1193,5,2000-12-28 23:45:35,M,18,4,61820,One Flew Over the Cuckoo's Nest (1975),Drama
11,42,1193,3,2000-12-28 22:29:41,M,25,8,24502,One Flew Over the Cuckoo's Nest (1975),Drama
12,44,1193,4,2000-12-28 16:56:35,M,45,17,98052,One Flew Over the Cuckoo's Nest (1975),Drama
13,47,1193,4,2000-12-28 05:39:05,M,18,4,94305,One Flew Over the Cuckoo's Nest (1975),Drama
14,48,1193,4,2000-12-28 04:44:21,M,25,4,92107,One Flew Over the Cuckoo's Nest (1975),Drama
15,49,1193,4,2001-01-06 21:46:12,M,18,12,77084,One Flew Over the Cuckoo's Nest (1975),Drama
16,53,1193,5,2000-12-27 20:46:40,M,25,0,96931,One Flew Over the Cuckoo's Nest (1975),Drama
17,54,1193,5,2000-12-27 20:07:19,M,50,1,56723,One Flew Over the Cuckoo's Nest (1975),Drama
18,58,1193,5,2000-12-27 17:17:46,M,25,2,30303,One Flew Over the Cuckoo's Nest (1975),Drama
19,59,1193,4,2000-12-27 17:24:52,F,50,1,55413,One Flew Over the Cuckoo's Nest (1975),Drama
20,62,1193,4,2000-12-28 02:56:24,F,35,3,98105,One Flew Over the Cuckoo's Nest (1975),Drama
21,80,1193,4,2000-12-26 00:16:12,M,56,1,49327,One Flew Over the Cuckoo's Nest (1975),Drama
22,81,1193,5,2000-12-26 00:11:04,F,25,0,60640,One Flew Over the Cuckoo's Nest (1975),Drama
23,88,1193,5,2000-12-24 22:42:41,F,45,1,02476,One Flew Over the Cuckoo's Nest (1975),Drama
24,89,1193,5,2000-12-24 19:46:36,F,56,9,85749,One Flew Over the Cuckoo's Nest (1975),Drama
25,95,1193,5,2000-12-24 03:57:12,M,45,0,98201,One Flew Over the Cuckoo's Nest (1975),Drama
26,96,1193,3,2000-12-24 02:36:29,F,25,16,78028,One Flew Over the Cuckoo's Nest (1975),Drama
27,99,1193,2,2001-02-21 22:30:53,F,1,10,19390,One Flew Over the Cuckoo's Nest (1975),Drama
28,102,1193,5,2002-12-24 14:46:47,M,35,19,20871,One Flew Over the Cuckoo's Nest (1975),Drama
29,104,1193,2,2000-12-23 05:43:40,M,25,12,00926,One Flew Over the Cuckoo's Nest (1975),Drama
...,...,...,...,...,...,...,...,...,...,...
1000179,4933,3084,3,2000-07-05 02:30:20,M,25,15,94040,Home Page (1999),Documentary
1000180,4802,2218,2,2002-02-28 04:24:16,M,56,1,40601,Juno and Paycock (1930),Drama
1000181,4812,2308,2,2000-07-07 03:13:11,M,18,14,25301,Detroit 9000 (1973),Action|Crime
1000182,4874,624,4,2000-07-05 09:25:18,F,25,4,70808,Condition Red (1995),Action|Drama|Thriller
1000183,5059,1434,4,2000-07-01 22:46:04,M,45,16,22652,"Stranger, The (1994)",Action
1000184,5947,1434,4,2000-05-01 16:13:48,F,45,16,97215,"Stranger, The (1994)",Action
1000185,5077,1868,3,2000-07-01 04:08:19,M,25,2,20037,"Truce, The (1996)",Drama|War
1000186,5944,1868,1,2000-05-01 18:12:00,F,18,10,27606,"Truce, The (1996)",Drama|War
1000187,5105,404,3,2000-06-30 05:59:42,M,50,7,18977,Brother Minister: The Assassination of Malcolm...,Documentary
1000188,5185,404,4,2000-07-12 13:50:17,F,35,4,44485,Brother Minister: The Assassination of Malcolm...,Documentary
1000189,5532,404,5,2000-05-29 19:04:01,M,25,17,27408,Brother Minister: The Assassination of Malcolm...,Documentary
1000190,5543,404,3,2000-06-04 16:06:32,M,25,17,97401,Brother Minister: The Assassination of Malcolm...,Documentary
1000191,5220,2543,3,2000-06-21 02:08:57,M,25,7,91436,Six Ways to Sunday (1997),Comedy
1000192,5754,2543,4,2000-05-14 04:45:16,F,18,1,60640,Six Ways to Sunday (1997),Comedy
1000193,5227,591,3,2000-06-20 06:38:51,M,18,10,64050,Tough and Deadly (1995),Action|Drama|Thriller
1000194,5795,591,1,2000-05-12 17:27:33,M,25,1,92688,Tough and Deadly (1995),Action|Drama|Thriller
1000195,5313,3656,5,2000-06-13 20:19:52,M,56,0,55406,Lured (1947),Crime
1000196,5328,2438,4,2000-06-12 21:27:55,F,25,4,91740,Outside Ozona (1998),Drama|Thriller
1000197,5334,3323,3,2000-06-12 09:49:19,F,56,13,46140,Chain of Fools (2000),Comedy|Crime
1000198,5334,127,1,2000-06-12 09:38:14,F,56,13,46140,"Silence of the Palace, The (Saimt el Qusur) (1...",Drama
1000199,5334,3382,5,2000-06-12 09:49:19,F,56,13,46140,Song of Freedom (1936),Drama
1000200,5420,1843,3,2000-06-05 00:08:25,F,1,19,14850,Slappy and the Stinkers (1998),Children's|Comedy
1000201,5433,286,3,2000-06-05 23:34:41,F,35,17,45014,Nemesis 2: Nebula (1995),Action|Sci-Fi|Thriller
1000202,5494,3530,4,2000-06-01 01:38:16,F,35,17,94306,Smoking/No Smoking (1993),Comedy
1000203,5556,2198,3,2000-05-27 18:38:35,M,45,6,92103,Modulations (1998),Documentary
1000204,5949,2198,5,2000-05-20 20:13:21,M,18,17,47901,Modulations (1998),Documentary
1000205,5675,2703,3,2000-12-05 16:11:56,M,35,14,30030,Broken Vessels (1998),Drama
1000206,5780,2845,1,2000-05-12 19:37:48,M,18,17,92886,White Boys (1999),Drama
1000207,5851,3607,5,2000-05-08 05:30:08,F,18,20,55410,One Little Indian (1973),Comedy|Drama|Western
1000208,5938,2909,4,2000-05-02 15:15:53,M,25,1,35401,"Five Wives, Three Secretaries and Me (1998)",Documentary

In [ ]:
def dameIndicePelicula (nombre):
    return peliculas.loc[peliculas['title'] == nombre].index.values[0]